// ── NEW 2026 MENU CONSTANTS ─────────────────────────────────────────────────
// Replace MENU_ODD and MENU_EVEN in the app's index.html with this content.
// Schema: {Day: {Meal: [{name, tags:[]}]}}  tags: "V"=Veg, "GF"=GlutenFree, "VG"=Vegan

function mi(name, ...tags){ return {name, tags}; }

const MENU_ODD = {
  Sun: {
    Dinner: [
      mi("Kalua Pork"),
      mi("Sushi Rice","V","GF","VG"),
      mi("Pasta Salad","V"),
      mi("Carrots & Broccoli","V","GF","VG"),
      mi("Katsu Sauce","V","GF","VG"),
      mi("Jackfruit Kalua","V","VG"),
      mi("Bug Juice","V","GF","VG"),
      mi("Jello","V"),
    ],
  },
  Mon: {
    Breakfast: [
      mi("Scrambled Eggs","V","GF"),
      mi("Sausage","GF"),
      mi("Potatoes O'Brien","V","GF","VG"),
      mi("Veggie Sausage","V"),
      mi("Cream of Wheat","V"),
      mi("Bug Juice","V","GF","VG"),
    ],
    Lunch: [
      mi("Chicken Udon Noodle Stir-Fry"),
      mi("Snap Peas & Veggies","V","GF","VG"),
      mi("Tofu Stir-Fry","V","VG"),
      mi("Water","V","GF","VG"),
    ],
    Dinner: [
      mi("BBQ Beef"),
      mi("Mac & Cheese","V"),
      mi("Peas and Carrots","V","GF","VG"),
      mi("Hawaiian Rolls","V"),
      mi("Mushrooms, Cauliflower & Eggplant in BBQ Sauce","V","VG"),
      mi("Bug Juice","V","GF","VG"),
      mi("Jello","V"),
    ],
  },
  Tue: {
    Breakfast: [
      mi("Pancakes","V"),
      mi("Bacon","GF"),
      mi("Hashbrowns","V","GF","VG"),
      mi("Veggie Sausage","V"),
      mi("Oatmeal","V","VG"),
      mi("Bug Juice","V","GF","VG"),
    ],
    Lunch: [
      mi("Beef Stroganoff"),
      mi("Garlic Noodles","V"),
      mi("Veggie Melody","V","GF","VG"),
      mi("Spinach & Mushroom Stroganoff","V"),
      mi("Water","V","GF","VG"),
    ],
    Dinner: [
      mi("Chicken Tacos"),
      mi("Cilantro-Lime Rice","V","GF","VG"),
      mi("Refried Beans","V","GF","VG"),
      mi("Flour Tortillas","V"),
      mi("Shredded Cheese","V","GF"),
      mi("Soyrizo Tacos","V","VG"),
      mi("Nopales","V","GF","VG"),
      mi("Mushrooms with Onions and Peppers","V","GF","VG"),
      mi("Bug Juice","V","GF","VG"),
      mi("Churros","V"),
    ],
  },
  Wed: {
    Breakfast: [
      mi("Biscuits & Gravy","V"),
      mi("Sausage"),
      mi("Potatoes","V","GF","VG"),
      mi("Veggie Sausage & Mushroom w/ Onion Gravy","V"),
      mi("Grits","V","GF"),
      mi("Bug Juice","V","GF","VG"),
    ],
    Lunch: [
      mi("Mongolian Beef"),
      mi("White Rice","V","GF","VG"),
      mi("Broccoli","V","GF","VG"),
      mi("Mongolian Fried Heart of Palm","V","VG"),
      mi("Water","V","GF","VG"),
    ],
    Dinner: [
      mi("Pizza","V"),
      mi("Cookies","V"),
    ],
  },
  Thu: {
    Breakfast: [
      mi("Scrambled Eggs","V","GF"),
      mi("English Muffin","V"),
      mi("Bacon","GF"),
      mi("Cheddar Cheese Slices","V","GF"),
      mi("Tater Tots","V","GF","VG"),
      mi("Veggie Bacon","V"),
      mi("Oatmeal","V","VG"),
      mi("Bug Juice","V","GF","VG"),
    ],
    Lunch: [
      mi("Sloppy Joes"),
      mi("Potato Salad","V","GF"),
      mi("Corn","V","GF","VG"),
      mi("Vegetarian Chili","V","VG"),
      mi("Baked Potato","V","GF","VG"),
      mi("Water","V","GF","VG"),
    ],
    Dinner: [
      mi("Orange Chicken"),
      mi("Lo Mein Stir-Fry"),
      mi("Cabbage & Veggie Melody","V","GF","VG"),
      mi("Tofu / Impossible Nuggets","V"),
      mi("Bug Juice","V","GF","VG"),
      mi("Fortune Cookies","V"),
    ],
  },
  Fri: {
    Breakfast: [
      mi("Chilaquiles (Eggs, Tortilla, Protein)","V"),
      mi("Refried Beans","V","GF","VG"),
      mi("Country Potatoes","V","GF","VG"),
      mi("Soyrizo","V","VG"),
      mi("Cream of Wheat","V"),
      mi("Bug Juice","V","GF","VG"),
    ],
    Lunch: [
      mi("BBQ Hamburgers"),
      mi("Potato Salad","V","GF"),
      mi("Chips","V","GF","VG"),
      mi("Toppings Bar","V","GF","VG"),
      mi("Veggie Patty","V"),
      mi("Water","V","GF","VG"),
    ],
    Dinner: [
      mi("Pot Roast"),
      mi("Mashed Potatoes","V","GF"),
      mi("Green Beans","V","GF","VG"),
      mi("Buns","V"),
      mi("Lentil Cabbage Rolls","V","VG"),
      mi("Bug Juice","V","GF","VG"),
      mi("Brownies","V"),
    ],
  },
  Sat: {
    Breakfast: [
      mi("Cold Cereal","V"),
      mi("Donuts","V"),
      mi("Cinnamon Rolls","V"),
      mi("Milk","V","GF"),
    ],
  },
};

const MENU_EVEN = {
  Sun: {
    Dinner: [
      mi("Kalua Pork"),
      mi("Sushi Rice","V","GF","VG"),
      mi("Pasta Salad","V"),
      mi("Carrots & Broccoli","V","GF","VG"),
      mi("Heart of Palm Kalua","V","VG"),
      mi("Bug Juice","V","GF","VG"),
      mi("Jello","V"),
    ],
  },
  Mon: {
    Breakfast: [
      mi("French Toast Sticks","V"),
      mi("Bacon","GF"),
      mi("Hashbrowns","V","GF","VG"),
      mi("Veggie Bacon","V"),
      mi("Oatmeal","V","VG"),
      mi("Bug Juice","V","GF","VG"),
    ],
    Lunch: [
      mi("BBQ Pulled Pork"),
      mi("Brioche Bun","V"),
      mi("Pickles & Coleslaw","V","GF","VG"),
      mi("Potato Wedges","V","GF","VG"),
      mi("BBQ Pulled Jackfruit","V","VG"),
      mi("Water","V","GF","VG"),
    ],
    Dinner: [
      mi("Cajun Chicken & Sausage"),
      mi("Penne Pasta","V"),
      mi("Holy Trinity Veggie Melody","V","GF","VG"),
      mi("Cajun Cauliflower Steak","V","VG"),
      mi("Bug Juice","V","GF","VG"),
      mi("French Beignets","V"),
    ],
  },
  Tue: {
    Breakfast: [
      mi("Scrambled Eggs","V","GF"),
      mi("Ham","GF"),
      mi("Cheddar Cheese Slices","V","GF"),
      mi("Croissant Sandwich","V"),
      mi("Tater Tots","V","GF","VG"),
      mi("Veggie Spinach, Mushrooms & Green Onion Scramble","V"),
      mi("Cream of Wheat","V"),
      mi("Bug Juice","V","GF","VG"),
    ],
    Lunch: [
      mi("Kung Pao Chicken"),
      mi("Egg Fried Rice","V"),
      mi("Veggie Stir-Fry","V","GF","VG"),
      mi("Kung Pao Tofu","V","GF","VG"),
      mi("Water","V","GF","VG"),
    ],
    Dinner: [
      mi("Beef Tacos"),
      mi("Cilantro-Lime Rice","V","GF","VG"),
      mi("Refried Beans","V","GF","VG"),
      mi("Flour Tortillas","V"),
      mi("Shredded Cheese","V","GF"),
      mi("Soyrizo Tacos","V","VG"),
      mi("Nopales","V","GF","VG"),
      mi("Mushrooms with Onions and Peppers","V","GF","VG"),
      mi("Bug Juice","V","GF","VG"),
      mi("Churros","V"),
    ],
  },
  Wed: {
    Breakfast: [
      mi("Biscuits & Gravy","V"),
      mi("Potatoes","V","GF","VG"),
      mi("Sausage"),
      mi("Veggie Sausage & Mushroom w/ Onion Gravy","V"),
      mi("Grits","V","GF"),
      mi("Bug Juice","V","GF","VG"),
    ],
    Lunch: [
      mi("Chicken Patty Sandwich"),
      mi("Lettuce, Tomato & Onion","V","GF","VG"),
      mi("Potato Chips","V","GF","VG"),
      mi("Impossible Nugget Sandwich","V"),
      mi("Water","V","GF","VG"),
    ],
    Dinner: [
      mi("Pizza","V"),
      mi("Cookies","V"),
    ],
  },
  Thu: {
    Breakfast: [
      mi("Scrambled Eggs","V","GF"),
      mi("Bacon","GF"),
      mi("Potatoes O'Brien","V","GF","VG"),
      mi("Veggie Bacon","V"),
      mi("Oatmeal","V","VG"),
      mi("Bug Juice","V","GF","VG"),
    ],
    Lunch: [
      mi("Turkey Corn Dog"),
      mi("Beef Chili Beans"),
      mi("Potato Salad","V","GF"),
      mi("Fruit Cup","V","GF","VG"),
      mi("Baked Potato","V","GF","VG"),
      mi("Vegetarian Chili","V","VG"),
      mi("Water","V","GF","VG"),
    ],
    Dinner: [
      mi("BBQ Chicken Drumsticks","GF"),
      mi("Mac & Cheese","V"),
      mi("Steamed Veggies","V","GF","VG"),
      mi("Hawaiian Rolls","V"),
      mi("Stuffed Bell Peppers","V","VG"),
      mi("Bug Juice","V","GF","VG"),
      mi("Frozen Fruit Slush","V","GF","VG"),
    ],
  },
  Fri: {
    Breakfast: [
      mi("Chilaquiles (Eggs, Tortilla, Protein)","V"),
      mi("Refried Beans","V","GF","VG"),
      mi("Country Potatoes","V","GF","VG"),
      mi("Soyrizo","V","VG"),
      mi("Cream of Wheat","V"),
      mi("Bug Juice","V","GF","VG"),
    ],
    Lunch: [
      mi("BBQ Hamburgers"),
      mi("Potato Salad","V","GF"),
      mi("Chips","V","GF","VG"),
      mi("Toppings Bar","V","GF","VG"),
      mi("Veggie Patty","V"),
      mi("Water","V","GF","VG"),
    ],
    Dinner: [
      mi("Pot Roast"),
      mi("Mashed Potatoes","V","GF"),
      mi("Green Beans","V","GF","VG"),
      mi("Buns","V"),
      mi("Lentil Cabbage Rolls","V","VG"),
      mi("Bug Juice","V","GF","VG"),
      mi("Brownies","V"),
    ],
  },
  Sat: {
    Breakfast: [
      mi("Cold Cereal","V"),
      mi("Donuts","V"),
      mi("Cinnamon Rolls","V"),
      mi("Milk","V","GF"),
    ],
  },
};
// ── END MENU CONSTANTS ──────────────────────────────────────────────────────
